// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WeatherService handles weather-related operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStoredLocation retrieves the stored weather location
 * @returns {$CancellablePromise<string>}
 */
export function GetStoredLocation() {
    return $Call.ByID(3432447403);
}

/**
 * GetWeather fetches weather data for a given location from Open-Meteo API
 * @param {string} location
 * @returns {$CancellablePromise<$models.WeatherData | null>}
 */
export function GetWeather(location) {
    return $Call.ByID(1811001601, location).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RefreshWeather refreshes the weather data and updates tray icon
 * @param {string} location
 * @returns {$CancellablePromise<$models.WeatherData | null>}
 */
export function RefreshWeather(location) {
    return $Call.ByID(2131631672, location).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetTrayUpdateFunc sets the function to update the tray icon
 * @param {any} updateFunc
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayUpdateFunc(updateFunc) {
    return $Call.ByID(1213703656, updateFunc);
}

/**
 * UpdateLocation updates the weather location in config
 * @param {string} location
 * @returns {$CancellablePromise<void>}
 */
export function UpdateLocation(location) {
    return $Call.ByID(4085311411, location);
}

// Private type creation functions
const $$createType0 = $models.WeatherData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
