// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct to hold application state and provide utility methods
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates checks if a new version is available
 * @returns {$CancellablePromise<$models.UpdateInfo | null>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DisableStartup disables the app from launching on system startup
 * @returns {$CancellablePromise<void>}
 */
export function DisableStartup() {
    return $Call.ByID(2374125532);
}

/**
 * EnableStartup enables the app to launch on system startup
 * @returns {$CancellablePromise<void>}
 */
export function EnableStartup() {
    return $Call.ByID(561757899);
}

/**
 * GetConfigPath returns the path to the config file
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigPath() {
    return $Call.ByID(4029735838);
}

/**
 * GetCurrentVersion returns the current app version
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentVersion() {
    return $Call.ByID(1827245900);
}

/**
 * GetDefaultConfig returns the default configuration
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function GetDefaultConfig() {
    return $Call.ByID(3182091318).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSetting gets a specific setting value
 * @param {string} key
 * @returns {$CancellablePromise<any>}
 */
export function GetSetting(key) {
    return $Call.ByID(48053349, key);
}

/**
 * HideWindow hides the main window
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(542966029);
}

/**
 * IsStartupEnabled checks if startup is enabled
 * @returns {$CancellablePromise<boolean>}
 */
export function IsStartupEnabled() {
    return $Call.ByID(3872694095);
}

/**
 * LoadConfig loads the application configuration
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function LoadConfig() {
    return $Call.ByID(2822453907).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MinimizeWindow minimizes the main window
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeWindow() {
    return $Call.ByID(1130157197);
}

/**
 * OpenReleaseURL opens the release page in the browser
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleaseURL(url) {
    return $Call.ByID(1293205979, url);
}

/**
 * PositionWindowNearTray positions the window near the system tray
 * @returns {$CancellablePromise<void>}
 */
export function PositionWindowNearTray() {
    return $Call.ByID(3354404992);
}

/**
 * SaveConfig saves the application configuration
 * @param {$models.AppConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(3442292638, config);
}

/**
 * SetSetting sets a specific setting value
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AppConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
