// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig represents the application configuration
 */
export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("windowWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("customSettings" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["customSettings"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customSettings" in $$parsedSource) {
            $$parsedSource["customSettings"] = $$createField4_0($$parsedSource["customSettings"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

/**
 * ForecastDay represents a single day forecast
 */
export class ForecastDay {
    /**
     * Creates a new ForecastDay instance.
     * @param {Partial<ForecastDay>} [$$source = {}] - The source object to create the ForecastDay.
     */
    constructor($$source = {}) {
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dayOfWeek"] = "";
        }
        if (!("maxTemp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxTemp"] = 0;
        }
        if (!("minTemp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minTemp"] = 0;
        }
        if (!("condition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["condition"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForecastDay instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForecastDay}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForecastDay(/** @type {Partial<ForecastDay>} */($$parsedSource));
    }
}

/**
 * UpdateInfo represents update information
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseUrl"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * WeatherData represents the weather information
 */
export class WeatherData {
    /**
     * Creates a new WeatherData instance.
     * @param {Partial<WeatherData>} [$$source = {}] - The source object to create the WeatherData.
     */
    constructor($$source = {}) {
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (!("temperature" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["temperature"] = 0;
        }
        if (!("feelsLike" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feelsLike"] = 0;
        }
        if (!("condition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["condition"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("humidity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["humidity"] = 0;
        }
        if (!("windSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windSpeed"] = 0;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastUpdated"] = "";
        }
        if (!("forecast" in $$source)) {
            /**
             * @member
             * @type {ForecastDay[]}
             */
            this["forecast"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeatherData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WeatherData}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forecast" in $$parsedSource) {
            $$parsedSource["forecast"] = $$createField9_0($$parsedSource["forecast"]);
        }
        return new WeatherData(/** @type {Partial<WeatherData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ForecastDay.createFrom;
const $$createType2 = $Create.Array($$createType1);
